pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        sh 'mvn clean verify'
      }
    }

    stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('sonarqube-local') {
          sh '''
            mvn sonar:sonar            
               -Dsonar.projectKey=my-app      
               -Dsonar.projectName="My App"   
               -Dsonar.host.url=$SONAR_HOST_URL
          '''
        }
      }
    }

    stage('Quality Gate') {
      steps {
        timeout(time: 10, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }
  }
}
